apiVersion: v1
kind: pod
metadata:
   name: nginx
   labels:
      purpose: demo

spec: #specifications of a pod
   containers: 
    - name: nginx #Multiple container can be there so starting with -
      image: nginx