apiVersion: v1
kind: Pod
metadata:
  name: multi-containers
  labels: 
    project: Roboshop
    purpose: multi-container-demo
spec:
  containers:
    - name: nginx
      image: nginx
    - name: almalinux
      image: almalinux:9
      command: ["sleep", "1000"] # TO KEEP CONTAINER RUNNING & BUSY , IF NOT CONTAINER WILL FAIL TO START
    
