apiVersion: v1
kind: Pod
metadata:
   name: labels
   label:
     project: roboshop
     environment: dev
     purpose: demo
     component: frontend

spec:
  containers:
      - name: nginx
        image: nginx