apiVersion: v1
kind: Pod
metadata:
   name: labels
   labels:
     project: Roboshop
     component: MySql
     tier: Backend
     environment: Dev
   annotations:
      description: "This pod is creted to demonstrate pod annotations"   
      jenkins: "https://www.jenkins.io/"  #THIS TYPE OF INFO CAN BE STORED UNDER ANNOTATIONS
spec:
  containers:
   - name: nginx
     image: nginx
  