apiVersion: v1
kind: Pod
metadata:
   name: environmentvariables
   labels:
      purpose: demo

spec: #specifications of a pod
   containers: 
    - name: nginx #Multiple container can be there so starting with -
      image: nginx
      env:
        - name: COURSE
          value: "KUBERENETS"

        - name: TRAINER
          value: "SIVAKUMAR"