apiVersion: v1
kind: ConfigMap
metadata:
  name: pod-config
  labels:
    purpose: config
    env: Dev
data:
  COURSE: "DevOps with AWS"
  DURATION: "150HRS"
  TRAINER: "SIVAKUMAR"

  # FOR THIS APPLY BELOW COOMND TO CHECK AFTER POD CREATION AS THIS WONT SHOW UNDER PODS
  #kubectl get configmap
