#SECRETS IS SAME LIKE CONFIG MAP BUT SECRETS WILL HAVE SECRET INFORMATION ENCODED , NOT NON SECRET INFO LIKE CONFIG MAP

apiVersion: v1
kind: Secret
metadata:
  name: pod-secret
  labels:
    purpose: secret
    env: dev
type: Opaque
data:
  username: "YWRtaW4="
  password: "YWRtaW4zMjE=" 
  
  # TO GET THESE ABOVE VALUES IN CMD USE BELOW MENTIONED COMMANDS
  # echo -n "ADMIN" | base 64 (any username we can give ) 
  # echo -n "admin134" | base 64 (any password we can give)