apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    purpose: service-demo
spec:
   selector: #HERE SELECTORS ARE LABELS (LABELS ARE SELECTORS,HERE THIS SERVICE WILL DEPEND ON LABLES TO SELECT AND WORK ON WHICH PODS)
    purpose: service-demo  
    project: roboshop
    environment: dev

ports:
   - protocol: TCP
     port: 80 #service port
     targetport: 80 #container port



---

apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    purpose: service-demo  #HERE WHICH POD LABELS ARE GIVEN WE NEED TO USE SAME LABELS AS SELECTORS IN ABOVE INSTRUCTIONS
    project: roboshop
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx